# Gradle Properties
org.gradle.jvmargs = -Xmx5G

loader_version = 0.18.4
quilt_parsers_version = 0.2.1

minecraft_version = 1.7.2
feather_build = 1

mod_version = 0.21.0-alpha.36
mod_artifact_id = osl-gen2
mod_maven_group = net.ornithemc
library_maven_group = net.ornithemc.osl-gen2

# mod.json
mod_id_short = osl
mod_id_long = ornithe-standard-libraries
mod_name_short = OSL
mod_name_long = Ornithe Standard Libraries
mod_description = Libraries and APIs for modding with Ornithe.
mod_contact_homepage = https://ornithemc.net/
mod_contact_issues = https://github.com/OrnitheMC/ornithe-standard-libraries/issues
mod_contact_sources = https://github.com/OrnitheMC/ornithe-standard-libraries
mod_license = Apache-2.0
mod_loader_dependency = >=0.18.0
