library_id = networking-impl
library_name = Networking Implementation
library_description = Implementation details of the Networking API.
library_version = 0.2.0

entrypoint_init = net.ornithemc.osl.networking.impl.Networking
entrypoint_client_init = net.ornithemc.osl.networking.impl.Networking
entrypoint_server_init = net.ornithemc.osl.networking.impl.Networking
osl_dependencies = core:>=0.7.0,entrypoints:>=0.5.0,lifecycle-events:>=0.6.0,executors:>=0.1.0,text-components:>=0.1.0-,networking:>=0.10.0
