package net.ornithemc.osl.items.impl.mixin.common;

import org.objectweb.asm.Opcodes;

import org.spongepowered.asm.mixin.Debug;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.At.Shift;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import com.llamalad7.mixinextras.expression.Definition;
import com.llamalad7.mixinextras.expression.Expression;
import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import com.llamalad7.mixinextras.injector.wrapoperation.WrapOperation;

import net.minecraft.block.Block;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;

import net.ornithemc.osl.blocks.impl.VanillaBlocks;
import net.ornithemc.osl.items.impl.ItemRegistryImpl;
import net.ornithemc.osl.items.impl.VanillaItems;

@Debug(export = true)
@Mixin(
	value = Block.class,
	priority = 1001 // make sure blocks mixin is applied first 
)
public class BlockMixin {

	/*
	 * Block and Item initialization is cursed AF prior to 13w36a.
	 * There are no registries, only arrays, and all initialization
	 * happens in the static initializer instead of a dedicated init
	 * method.
	 * 
	 * In general the order of operations is as follows:
	 * 1. Block::<clinit>
	 *   1.1. construct all blocks
	 *   1.2. Item::<clinit>
	 *     1.2.1 construct all regular items
	 *     1.2.2 init regular item stats
	 *   1.3. init special block items
	 *   1.4. auto-generate remaining block items
	 *   1.5. init block item stats
	 * But this is not always the case. In Alpha and early Beta versions,
	 * Item::<clinit> happens before all blocks have been initialized.
	 * 
	 * To mess with this order as little as possible, there are two item
	 * registration events: one for regular items and one for block items.
	 * 
	 * The regular item registration event is fired in Item::<clinit>,
	 * after Vanilla items have been initialized.
	 * 
	 * The block item registration even is fired in Block::<clinit>, so
	 * that block item stats initialize correctly, but *before* Vanilla
	 * block items are initialized. This is because Vanilla auto-generates
	 * most block items, but we want to allow mods to register special
	 * item forms for their blocks.
	 */

	@Inject(
		method = "<clinit>",
		at = @At(
			// inject before the for-loop for auto block item generation
			value = "JUMP",
			opcode = Opcodes.IF_ICMPGE,
			shift = Shift.BY,
			// it's extreme but this ensures that the injector is only invoked once
			by = -5
		)
	)
	private static void osl$items$registerBlockItems(CallbackInfo ci) {
		// trigger Item class init in Beta 1.1 and below
		// it would otherwise be triggered in the for-loop anyway
		Item.BY_ID.getClass();

		ItemRegistryImpl.registerBlockItems();
	}

	@WrapOperation(
		method = "<clinit>",
		at = @At(
			value = "NEW",
			target = "net/minecraft/item/BlockItem"
		)
	)
	private static BlockItem osl$items$cancelAutoGeneratedBlockItem(int id, Operation<BlockItem> op) {
		Block block = Block.BY_ID[id + VanillaItems.ITEM_ID_OFFSET];

		if (block.isAir() || ItemRegistryImpl.BLOCK_ITEMS.containsKey(block)) {
			return null;
		} else {
			// for Vanilla block items, ensure block ID == item ID
			// for custom mod items, let Items API assign a new ID
			if (block.id > VanillaBlocks.MAX_ID) {
				id = Item.AUTO_ASSIGN_ID;
			}

			return op.call(id);
		}
	}

	@Definition(
		id = "BY_ID",
		field = "Lnet/minecraft/item/Item;BY_ID:[Lnet/minecraft/item/Item;"
	)
	@Expression("BY_ID[?] = ?")
	@WrapOperation(
		method = "<clinit>",
		at = @At(
			value = "MIXINEXTRAS:EXPRESSION"
		)
	)
	private static void osl$items$cancelPutBlockItemInArray(Item[] BY_ID, int id, Item item, Operation<Item> op) {
	}
}
