package net.ornithemc.osl.items.impl.mixin.common;

import org.objectweb.asm.Opcodes;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.Slice;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import com.llamalad7.mixinextras.injector.wrapoperation.WrapOperation;
import com.llamalad7.mixinextras.sugar.Share;
import com.llamalad7.mixinextras.sugar.ref.LocalBooleanRef;
import com.llamalad7.mixinextras.sugar.ref.LocalRef;

import net.minecraft.block.Block;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;

import net.ornithemc.osl.items.impl.ItemRegistryImpl;

@Mixin(Block.class)
public class BlockMixin {

	/*
	 * Block and Item initialization is cursed AF prior to 13w36a.
	 * There are no registries, only arrays, and all initialization
	 * happens in the static initializer instead of a dedicated init
	 * method.
	 * 
	 * In general the order of operations is as follows:
	 * 1. Block::<clinit>
	 *   1.1. construct all blocks
	 *   1.2. Item::<clinit>
	 *     1.2.1 construct all regular items
	 *     1.2.2 init regular item stats
	 *   1.3. init special block items
	 *   1.4. auto-generate remaining block items
	 *   1.5. init block item stats
	 * But this is not always the case. In Alpha and early Beta versions,
	 * Item::<clinit> happens before all blocks have been initialized.
	 * 
	 * To mess with this order as little as possible, there are two item
	 * registration events: one for regular items and one for block items.
	 * 
	 * The regular item registration event is fired in Item::<clinit>,
	 * after Vanilla items have been initialized.
	 * 
	 * The block item registration even is fired in Block::<clinit>, so
	 * that block item stats initialize correctly, but *before* Vanilla
	 * block items are initialized. This is because Vanilla auto-generates
	 * most block items, but we want to allow mods to register special
	 * item forms of their blocks.
	 */

	@Inject(
		method = "<clinit>",
		slice = @Slice(
			from = @At(
				value = "FIELD",
				opcode = Opcodes.PUTSTATIC,
				target = "Lnet/minecraft/block/Block;STONE:Lnet/minecraft/block/Block;"
			)
		),
		at = @At(
			value = "FIELD",
			target = "Lnet/minecraft/item/Item;BY_ID:[Lnet/minecraft/item/Item;",
			ordinal = 0
		)
	)
	private static void osl$items$registerBlockItems(CallbackInfo ci, @Share("osl$items$blockItemsRegistered") LocalBooleanRef blockItemsRegistered) {
		// in some versions this injector targets a for-loop
		if (!blockItemsRegistered.get()) {
			// Item registration would be initiated here anyway
			// force it to happen *before* we register block items
			Item.BY_ID.getClass();

			ItemRegistryImpl.registerBlocks();
		}

		blockItemsRegistered.set(true);
	}

	@WrapOperation(
		method = "<clinit>",
		at = @At(
			value = "NEW",
			target = "net/minecraft/item/BlockItem"
		)
	)
	private static BlockItem osl$items$cancelAutoGeneratedBlockItem(int id, Operation<BlockItem> op) {
		if (ItemRegistryImpl.BLOCK_ITEMS.containsKey(Block.BY_ID[id + 256])) {
			return null;
		} else {
			return op.call(id);
		}
	}

	@WrapOperation(
		method = "<clinit>",
		at = @At(
			value = "FIELD",
			target = "Lnet/minecraft/item/Item;BY_ID:[Lnet/minecraft/item/Item;",
			opcode = Opcodes.GETSTATIC,
			args = "array=set"
		)
	)
	private static Item[] osl$items$cancelPutBlockItemInArray(Operation<Void> op, @Share("osl$items$dummyItemArray") LocalRef<Item[]> dummyItems) {
		// operation is unnecessary as Item::<init> already puts the item in the array
		if (dummyItems.get() == null) {
			dummyItems.set(new Item[Item.BY_ID.length]);
		}

		return dummyItems.get();
	}
}
