library_id = registries
library_name = Registries
library_description = Registries API and numerical ID synchronization.
library_version = 0.1.0-alpha.14

entrypoint_client_init = net.ornithemc.osl.registries.impl.RegistriesEntrypoint
osl_dependencies = core:>=0.8.0,entrypoints:>=0.5.0,lifecycle-events:>=0.6.0,executors:>=0.1.0,text-components:>=0.1.0-,networking:>=0.9.0,networking-impl:>=0.1.0
