library_id = config
library_name = Config
library_description = A config library.
library_version = 0.6.2-alpha.1

entrypoint_init = net.ornithemc.osl.config.impl.ConfigInitializer
entrypoint_client_init = net.ornithemc.osl.config.impl.client.ClientConfigInitializer
entrypoint_server_init = net.ornithemc.osl.config.impl.server.ServerConfigInitializer
osl_dependencies = core:>=0.7.0,entrypoints:>=0.5.0,lifecycle-events:>=0.6.0
