library_id = data-gen
library_name = Data Gen
library_description = Data Generator api.
library_version = 0.1.0-alpha.1

entrypoint_init = net.ornithemc.osl.datagen.impl.DataGeneratorInit
osl_dependencies = core:0.8.0,entrypoints:0.5.0,registries:0.1.0,resource-loader:0.8.0,blocks:0.2.0,items:0.2.0
