library_id = branding
library_name = Branding
library_description = Branding API for patching the title screen and debug overlay.
library_version = 0.4.2-alpha.2

entrypoint_client_init = net.ornithemc.osl.branding.impl.BrandingPatchImpl
osl_dependencies = core:>=0.7.0,entrypoints:>=0.5.0,lifecycle-events:>=0.6.0
