library_id = resource-loader
library_name = Resource Loader
library_description = Resource loading API and events.
library_version = 0.5.4

entrypoint_init = net.ornithemc.osl.resource.loader.impl.ResourceLoader
entrypoint_client_init = net.ornithemc.osl.resource.loader.impl.ResourceLoader
osl_dependencies = core:>=0.4.0,entrypoints:>=0.2.0,lifecycle-events:>=0.4.0
